name: Setup uipathcli
description: Installs the uipathcli tool on a github actions runner
author: Mikael Andersson

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

runs:
  using: node20
  main: dist/index.js
